### ISSUE TITLE
iOS Safari compatibility

### ISSUE THREAD

**Issue by gerryDiacon** [ivmartel/dwv-react#102]
Hi,

Great tools for viewing DICOM files. I have one question. Is this compatible with the latest ios Safari? Because when we try to open our web app from iphone it's always restarting progress at 50%. No problem with Safari in iPadOS or macOS though. We are trying to use web inspector and give a console.log at progress event. But web keep reload from 0 but the console log stuck at 50. There is no sign of error logged

Thanks.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/50445981/127461529-a687f20d-bf6b-4d27-9e06-d4850ef2ae9c.png">

**Comment by ivmartel** [comment]
Sorry for answering so late, I do not have devices to test this, I'll tell you if I find some!

**Comment by ivmartel** [comment]
Sorry, I lost track of this issue... I hope you found a solution.

Closing for now, feel free to comment if you need.
