### ISSUE TITLE
Drag'n'Drop critical bug

### ISSUE THREAD

**Issue by GlosusHidden** [ivmartel/dwv-react#105]
Hello. 

To reproduce the bug, you need to:
- open DICOM file
- select "Draw"
- draw line
- drag it. Not by line, but by tooltip

![image](https://user-images.githubusercontent.com/56901000/128156467-d5d496c1-9988-40a1-b795-337d18e48c4b.png)

In addition to the console error, the components starts making hundreds of requests to the server and freezes.

**Comment by ivmartel** [comment]
Ok, confirmed! I created [dwv/issues/994](https://github.com/ivmartel/dwv/issues/994) to fix it.

**Comment by ivmartel** [comment]
This should be fixed with the update of dwv to v0.30.
