### ISSUE TITLE
Getting "Cannot Read properties of null"

### ISSUE THREAD

**Issue by yashwanthkorla** [ivmartel/dwv-react#109]
Hi,

While trying to reset or choose a different tool, I am getting the below error. It's as if the app object doesn't exist. Could you please help me with this?

![image](https://user-images.githubusercontent.com/4706215/135213413-6a0c8009-d047-4064-97ab-63f87f91805f.png)

**Comment by ivmartel** [comment]
Sorry, I lost track of this issue... I hope you found a solution.

Closing for now, feel free to comment if you need.
