### ISSUE TITLE
How do I upload multiple files so that we can view side by side?

### ISSUE THREAD

**Issue by prameetc** [ivmartel/dwv-react#111]
I would like to upload multiple images that can be viewed side by side, is that possible?

**Comment by ivmartel** [comment]
For now you need to instantiate two different viewers (`dwv.App`). The next release (dwv 0.30.0) should allow you to do this with one viewer.

**Comment by ivmartel** [comment]
The new dwv (v0.30) allows for this. I'll try to update the demo to show how to do it.
