### ISSUE TITLE
Any exemple of a viewer in a Functional Component?

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv-react#124]
Do you have any exemples or can confirm me that it's possible to create a viewer in a functional component?

**Comment by ivmartel** [comment]
The current implementation is a [class component](https://reactjs.org/docs/react-component.html). [Functional components](https://reactjs.org/docs/components-and-props.html) looked too limited, I'm not sure you could fit all the logic in one. So, no I do not have any examples. Why do you want a functional component?

**Comment by XaloDev** [comment]
I need to use with an WebGL Component and for me is more easy with functional components. I tried and managed to implement successfully, thank you.

**Comment by ivmartel** [comment]
If you can share some of your code and/or findings, that would be cool.
