### ISSUE TITLE
Can you do a MPR example?

### ISSUE THREAD

**Issue by icaroxavier** [ivmartel/dwv-react#129]
Can you do a select example to change the visualization mode like the dwv viewer? Axial, Coronal and Sagittal.

**Comment by ivmartel** [comment]
I'll see if I can find some time...

Originates from https://github.com/ivmartel/dwv/issues/1097

**Comment by ivmartel** [comment]
Took me time! See #204 and also the dwv test viewer ([tests/pacs/viewer.html](https://github.com/ivmartel/dwv/blob/v0.31.0/tests/pacs/viewer.html)).

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
