### ISSUE TITLE
Can I integrate Socket.io with dwv-react ? 

### ISSUE THREAD

**Issue by srivastavadevesh124** [ivmartel/dwv-react#233]
I want to integrate [socket.io](https://socket.io/) features with dwv so that whenever users connect to the same socket.io event and if one user uploads a dicom image then it should show in the viewer of other users who are connected too . is it possible ? please help

**Comment by ivmartel** [comment]
Sorry, I have no experience with socket.io...

**Comment by ivmartel** [comment]
Closing for now, see the dwv issue for progress.
