### ISSUE TITLE
Error coming when i am toggling from fullscreen view to normal view 

### ISSUE THREAD

**Issue by srivastavadevesh124** [ivmartel/dwv-react#234]
So I have put a feature to view dicom viewer in fullscreen and whenever i am toggling the fullscreen mode and exiting it . I am getting this error : `Error: Cannot fit to zero sized container.` . Can anyone tell what kind of error is this . 
I am using nextjs with javascript in my app .

**Comment by ivmartel** [comment]
This error happens when the html div where the viewer tries to add a canvas does not provide width and height. It probably happens because the html is not ready (the div is not created) when you call the viewer render.

**Comment by ivmartel** [comment]
I hope you found a solution to your problem.

Closing for now, feel free to comment if you need.
