### ISSUE TITLE
Customizing UI

### ISSUE THREAD

**Issue by junxiant** [ivmartel/dwv-react#242]
Hello, 

I'm currently using this viewer for my project, I would like to ask how easy would it be to customize the UI? 

1. I would like to include the window level values 
2. Current slice number

**Comment by ivmartel** [comment]
What you are asking should be easy, check out the demo viewer ([pacs/viewer.js](https://github.com/ivmartel/dwv/blob/develop/tests/pacs/viewer.js) that you launch with `yarn run start`) and the scroll [examples](https://ivmartel.github.io/dwv/doc/stable/Scroll.html#Scroll).

**Comment by junxiant** [comment]
Thanks, I'll take a look at it and try it out

**Comment by ivmartel** [comment]
I hope you found what you were looking for.

Closing for now, feel free to comment if you need.
