### ISSUE TITLE
Additional tools in React implementation

### ISSUE THREAD

**Issue by BrianMcRails** [ivmartel/dwv-react#3]
Hey man,

How would you go about adding the other tools, for instance Tags, to this React implementation? Been trying to get it working myself that past week or so but haven’t had success so I thought it was time to throw the question up to you. Let me know if you have any guidance.

Thanks

**Comment by ivmartel** [comment]
Adding more tools is on the plan and starting with the tags looks like a good idea, I'll look into that. 

I've been looking at adding drawings and could not make it work out of the box, this can come next...

**Comment by ivmartel** [comment]
By the way, any recommendations on UI components? [material-ui](http://www.material-ui.com), [react-bootstrap](https://react-bootstrap.github.io/) or another?

Any suggestions as to how to display all the tools in a nice and efficient way are welcome!

**Comment by BrianMcRails** [comment]
I've had the most enjoyment and the best results with [material-ui-next](https://material-ui-next.com/), although I think for something like DICOM tags react-bootstrap might work better because the components aren't as big, so you can fit more data. If you want to be trendy I've heard people really like [styled-components](https://github.com/styled-components/styled-components) but i haven't used it before. In any case it boils down to what you think looks best and what you're most comfortable working with. You can't really go wrong with any of those choices.

[material-ui-next-table](https://material-ui-next.com/demos/tables/) seems like a good simple candidate for displaying DICOM tag info.

**Comment by ivmartel** [comment]
I created #9 for the tags and will create specific issues for next features.
