### ISSUE TITLE
How to apply filter

### ISSUE THREAD

**Issue by KhangNg92** [ivmartel/dwv-react#51]
I'm trying to apply the filter e.g **Threshold, Sobel, Sharpen**, but still having difficulties to dig into it. I've been searching for docs on dwv site but still haven't had any clues to use it correctly. Please help me figure it out. Any help would be much appreciated it. Thank you for the awesome library and have a great week :). Looking forward for the reply

**Comment by ivmartel** [comment]
I've not tried this yet, but it is next on my list after the dwv 0.27 release.

**Comment by ivmartel** [comment]
I created #59 to add filters to the viewer. Stay tuned. Closing this issue for now.
