### ISSUE TITLE
Decoded UTF-16 Binary read

### ISSUE THREAD

**Issue by rheosai** [ivmartel/dwv-react#55]
Hi, 

I was wondering if there was a way to either read UTF-16 decoded binary or receive data as a byte array. I am not allowed to get DICOM directly from the file store and it has to pass through an intermediate microservice(for authorization). If so, can you point me to the relevant section of code for implementation/modification.

**Comment by ivmartel** [comment]
The dwv application class provides a [loadImageObject](https://github.com/ivmartel/dwv/blob/v0.26.0/src/app/application.js#L552) method to load `ArrayBuffers`.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
