### ISSUE TITLE
About new update

### ISSUE THREAD

**Issue by arunjoshtech** [ivmartel/dwv-react#62]
Are you updating new tools with this package? And migrate to latest reactjs versions?
Is it available with Typescript?

**Comment by ivmartel** [comment]
I'll maybe have more time to add tools soon...
This project is using React 16.13.1 which is the latest version.
dwv does not provide typescript bindings for now, see [dwv/issues/669](https://github.com/ivmartel/dwv/issues/669) for progress.

**Comment by ivmartel** [comment]
Now using react 16.14 and material-ui v4. Closing for now, feel free to comment if you need!
