### ISSUE TITLE
When update the dwv version then it throws  issues

### ISSUE THREAD

**Issue by ruchi1234** [ivmartel/dwv-react#82]
Hi, I have updated the version of dwv for using multiple files in URL like this 
https://github.com/ivmartel/dwv/issues/841

But now I am getting this issue - **and also please guide me to use multiple url in the input parameter without using DICOM ROOT all files comes from different places** 
![issuess](https://user-images.githubusercontent.com/273250/109255433-fbdcd000-7819-11eb-9fba-8ef4960be783.png)

**Comment by ivmartel** [comment]
Relates to #75.
