### ISSUE TITLE
How do I pass mutiple dicom files as a parameter url

### ISSUE THREAD

**Issue by ruchi1234** [ivmartel/dwv-react#97]
I am using Dicom viewer on Reactjs - I am using the version - "dwv": "^0.27.1 ", 
For some dicom files it gives me that error- 
![image](https://user-images.githubusercontent.com/273250/121639719-9354ee80-caaa-11eb-8b0b-e8807719d580.png)

And also I need to use multiple Dicom files URL in the Dicom input - parameter URL, For that, I have posted this question
https://github.com/ivmartel/dwv/issues/841
But still, I am not getting any solution.
All files have a unique address and I do not have a Dicom root address.

**Comment by ruchi1234** [comment]
I am still waiting for a response

**Comment by ivmartel** [comment]
Hi! Do you have more details about the failing files? The react demo seems to have some troubles with JPEG encoded data (transfer syntax: 1.2.840.10008.1.2.4.*).
For your other problem, the related [dwv/issues/843](https://github.com/ivmartel/dwv/issues/843) is fixed, if you still have troubles, please comment on it.

**Comment by ivmartel** [comment]
Closing for now, I hope I answered your question. Feel free to comment if you need.
