### ISSUE TITLE
Error on property fitToContainer to launch website

### ISSUE THREAD

**Issue by trans-iesa** [ivmartel/dwv-react#99]
Hi, this project solution is great!, but some error was found: 

This error say "Uncaught TypeError: Cannot read property 'fitToContainer' of null
    at w.App.fitToContainer (dwv.min.js:3)
    at onResize (dwv.min.js:3)"

and the file dicom attached doesn't be loaded ( see image and image2) 

![image](https://user-images.githubusercontent.com/44677003/124933591-637e0580-dfda-11eb-9ed7-d6fc5d5f4eec.JPG)
![image2](https://user-images.githubusercontent.com/44677003/124934248-ee5f0000-dfda-11eb-9a47-db405f911601.JPG)
}
Any possible solution please let me know.
Thanks for your time!

**Comment by ivmartel** [comment]
This error is in the core library (dwv) and was fixed in this [commit](https://github.com/ivmartel/dwv/commit/24e5dfa), but it will be available in the next release...
